# Generated by Django 5.0.2 on 2024-04-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_offer',
            field=models.BooleanField(default=False),
        ),
    ]
