# Generated by Django 5.0.1 on 2024-02-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_value',
            new_name='variation_color',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_category',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_size',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
