# Generated by Django 5.0.1 on 2024-02-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_variation_value_variation_variation_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
