# Generated by Django 5.0.1 on 2024-03-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_cart_item_variations'),
        ('product', '0006_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
