# Generated by Django 5.0.1 on 2024-02-14 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('product', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='has_offer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.offer'),
            preserve_default=False,
        ),
    ]
