# Generated by Django 5.0.1 on 2024-02-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_coupon'),
        ('product', '0004_rename_variation_value_variation_variation_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.variation'),
            preserve_default=False,
        ),
    ]
