# Generated by Django 5.0.1 on 2024-02-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_item_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='variation',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='variation_color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_item',
            name='variation_size',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
