# Generated by Django 5.0.2 on 2024-05-15 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.coupon'),
            preserve_default=False,
        ),
    ]
