# Generated by Django 5.0.2 on 2024-05-15 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_item_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.coupon'),
        ),
    ]
