# Generated by Django 5.0.1 on 2024-03-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_cart_item_cart_cart_item_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='variations',
        ),
    ]
