# Generated by Django 5.0.1 on 2024-03-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cart_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='variations',
        ),
    ]
