# Generated by Django 5.0.1 on 2024-03-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_remove_cart_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='is_active',
        ),
    ]
